// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCelXSbi-HEgO4b4lNm2-WM_wz3tA7wqoI',
    appId: '1:325279130986:web:abcf26b121220a1c9bf113',
    messagingSenderId: '325279130986',
    projectId: 'flutter-project-e3da7',
    authDomain: 'flutter-project-e3da7.firebaseapp.com',
    storageBucket: 'flutter-project-e3da7.firebasestorage.app',
    measurementId: 'G-CBM9YVYC42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsexR1yduwqm3ICLiukSNSdB1k8Wkvcmo',
    appId: '1:325279130986:android:6158ba750806480b9bf113',
    messagingSenderId: '325279130986',
    projectId: 'flutter-project-e3da7',
    storageBucket: 'flutter-project-e3da7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCelXSbi-HEgO4b4lNm2-WM_wz3tA7wqoI',
    appId: '1:325279130986:web:56ef0553f5fac2f69bf113',
    messagingSenderId: '325279130986',
    projectId: 'flutter-project-e3da7',
    authDomain: 'flutter-project-e3da7.firebaseapp.com',
    storageBucket: 'flutter-project-e3da7.firebasestorage.app',
    measurementId: 'G-N279KNL9V5',
  );
}
